"""baseline schema

Revision ID: 25b65b3b02f6
Revises: 
Create Date: 2026-07-28 18:50:42.275997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b65b3b02f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('knowledge_map_json', sa.Text(), nullable=True),
    sa.Column('questions_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('group', sa.Enum('CONTROL', 'TREATMENT', name='studygroup'), nullable=False),
    sa.Column('pre_test_score', sa.Float(), nullable=True),
    sa.Column('post_test_score', sa.Float(), nullable=True),
    sa.Column('share_code', sa.String(length=12), nullable=True),
    sa.Column('recovery_token_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_recovery_token_hash'), ['recovery_token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_share_code'), ['share_code'], unique=True)

    op.create_table('cognitive_fingerprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('profile_json', sa.Text(), nullable=True),
    sa.Column('bandit_state_json', sa.Text(), nullable=True),
    sa.Column('last_rebuild_status', sa.String(length=16), nullable=True),
    sa.Column('last_rebuild_at', sa.DateTime(), nullable=True),
    sa.Column('last_rebuild_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('cognitive_fingerprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cognitive_fingerprints_id'), ['id'], unique=False)

    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('technique', sa.Enum('SPACED_REPETITION', 'ACTIVE_RECALL', 'RE_READING', 'MIND_MAPS', 'INTERLEAVING', 'ELABORATIVE_INTERROGATION', 'PRACTICE_TESTING', name='studytechnique'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('time_of_day', sa.Enum('MORNING', 'AFTERNOON', 'EVENING', 'NIGHT', name='timeofday'), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('quiz_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_sessions_id'), ['id'], unique=False)

    op.create_table('retention_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('check_type', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retention_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retention_checks_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retention_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retention_checks_id'))

    op.drop_table('retention_checks')
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_sessions_id'))

    op.drop_table('study_sessions')
    with op.batch_alter_table('cognitive_fingerprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cognitive_fingerprints_id'))

    op.drop_table('cognitive_fingerprints')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_share_code'))
        batch_op.drop_index(batch_op.f('ix_users_recovery_token_hash'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_id'))

    op.drop_table('materials')
    # ### end Alembic commands ###
