"""email auth: magic link tokens and user email

Revision ID: 71c5e16382ae
Revises: 25b65b3b02f6
Create Date: 2026-08-05 23:12:15.354584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c5e16382ae'
down_revision: Union[str, Sequence[str], None] = '25b65b3b02f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magic_link_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('magic_link_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_magic_link_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_magic_link_tokens_token_hash'), ['token_hash'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_reminder_sent_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('last_reminder_sent_at')
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('email')

    with op.batch_alter_table('magic_link_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_magic_link_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_magic_link_tokens_id'))

    op.drop_table('magic_link_tokens')
    # ### end Alembic commands ###
