"""analytics events

Revision ID: 78c4edbf80cb
Revises: 71c5e16382ae
Create Date: 2026-08-05 23:23:58.137073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c4edbf80cb'
down_revision: Union[str, Sequence[str], None] = '71c5e16382ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('properties_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_event_name'), ['event_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_events_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_event_name'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_created_at'))

    op.drop_table('analytics_events')
    # ### end Alembic commands ###
